SET XACT_ABORT ON

BEGIN TRANSACTION QUICKDBD

CREATE TABLE [CUSTOMER] (
    [CUST_ID] CHAR(3)  NOT NULL ,
    [FIRST_NAME] VARCHAR(20)  NOT NULL ,
    [LAST_NAME] VARCHAR(20)  NOT NULL ,
    [ADDRESS] VARCHAR(20)  NOT NULL ,
    [CITY] VARCHAR(15)  NOT NULL ,
    [STATE] CHAR(2)  NOT NULL ,
    [POSTAL] CHAR(5)  NOT NULL ,
    [CELL_POHONE] CHAR(12)  NOT NULL ,
    [REP_ID] CHAR(2)  NOT NULL ,
    [BALANCE] tinyint  NOT NULL ,
    [CREDIT_LIMIT] tinyint  NOT NULL ,
    CONSTRAINT [PK_CUSTOMER] PRIMARY KEY CLUSTERED (
        [CUST_ID] ASC
    )
)

CREATE TABLE [SALES_REP] (
    [REP_ID] CHAR(2)  NOT NULL ,
    [REP_FIRST_NAME] VARCHAR(20)  NOT NULL ,
    [REP_LAST_NAME] VARCHAR(20)  NOT NULL ,
    [ADDRESS] VARCHAR(20)  NOT NULL ,
    [CITY] VARCHAR(15)  NOT NULL ,
    [STATE] CHAR(2)  NOT NULL ,
    [POSTAL] CHAR(5)  NOT NULL ,
    [CELL_POHONE] CHAR(12)  NOT NULL ,
    [COMMISSION] DECIMAL(3,2)  NOT NULL ,
    [RATE] DECIMAL(3,2)  NOT NULL ,
    CONSTRAINT [PK_SALES_REP] PRIMARY KEY CLUSTERED (
        [REP_ID] ASC
    )
)

CREATE TABLE [INVOICES] (
    [INVOICE_NUM] CHAR(5)  NOT NULL ,
    [INVOICE_DATE] DATE  NOT NULL ,
    [CUST_ID] CHAR(3)  NOT NULL ,
    CONSTRAINT [PK_INVOICES] PRIMARY KEY CLUSTERED (
        [INVOICE_NUM] ASC
    )
)

CREATE TABLE [INVOICE_LINE] (
    [INVOICE_NUM] CHAR(5)  NOT NULL ,
    [ITEM_ID] CHAR(4)  NOT NULL ,
    [QUANTITY] NUMERIC  NOT NULL ,
    [QUOTED_PRICE] DECIMAL(3,2)  NOT NULL ,
    CONSTRAINT [PK_INVOICE_LINE] PRIMARY KEY CLUSTERED (
        [INVOICE_NUM] ASC
    )
)

CREATE TABLE [ITEM] (
    [ITEM_ID] CHAR(4)  NOT NULL ,
    [DESCRIPTION] VARCHAR(30)  NOT NULL ,
    [ON_HAND] NUMERIC  NOT NULL ,
    [CATEGORY] CHAR(3)  NOT NULL ,
    [LOCATION] CHAR(1)  NOT NULL ,
    [PRICE] DECIMAL(3,2)  NOT NULL ,
    CONSTRAINT [PK_ITEM] PRIMARY KEY CLUSTERED (
        [ITEM_ID] ASC
    )
)

ALTER TABLE [CUSTOMER] WITH CHECK ADD CONSTRAINT [FK_CUSTOMER_REP_ID] FOREIGN KEY([REP_ID])
REFERENCES [SALES_REP] ([REP_ID])

ALTER TABLE [CUSTOMER] CHECK CONSTRAINT [FK_CUSTOMER_REP_ID]

ALTER TABLE [INVOICES] WITH CHECK ADD CONSTRAINT [FK_INVOICES_INVOICE_NUM] FOREIGN KEY([INVOICE_NUM])
REFERENCES [INVOICE_LINE] ([INVOICE_NUM])

ALTER TABLE [INVOICES] CHECK CONSTRAINT [FK_INVOICES_INVOICE_NUM]

ALTER TABLE [INVOICES] WITH CHECK ADD CONSTRAINT [FK_INVOICES_CUST_ID] FOREIGN KEY([CUST_ID])
REFERENCES [CUSTOMER] ([CUST_ID])

ALTER TABLE [INVOICES] CHECK CONSTRAINT [FK_INVOICES_CUST_ID]

ALTER TABLE [INVOICE_LINE] WITH CHECK ADD CONSTRAINT [FK_INVOICE_LINE_ITEM_ID] FOREIGN KEY([ITEM_ID])
REFERENCES [ITEM] ([ITEM_ID])

ALTER TABLE [INVOICE_LINE] CHECK CONSTRAINT [FK_INVOICE_LINE_ITEM_ID]

COMMIT TRANSACTION QUICKDBD