-- TASK 1
SELECT ITEM_ID, DESCRIPTION, PRICE
FROM ITEM;

-- TASK 2
SELECT * FROM INVOICES;

-- TASK 3
SELECT FIRST_NAME, LAST_NAME
FROM CUSTOMER
WHERE CREDIT_LIMIT >= '1000';

-- TASK 4
SELECT INVOICE_NUM
FROM INVOICES
WHERE CUST_ID = '125' AND INVOICE_DATE = '2021-11-15';

-- TASK 5
SELECT CUST_ID, FIRST_NAME, LAST_NAME
FROM CUSTOMER
WHERE REP_ID = '10' OR REP_ID = '15';

-- TASK 6
SELECT ITEM_ID, DESCRIPTION
FROM ITEM
WHERE CATEGORY <> 'HOR';

-- TASK 7
SELECT ITEM_ID, DESCRIPTION, ON_HAND
FROM ITEM
WHERE ON_HAND BETWEEN 10 AND 30;

-- TASK 8
SELECT ITEM_ID, DESCRIPTION, (ON_HAND * PRICE) AS ON_HAND_VALUE
FROM ITEM
WHERE CATEGORY = 'CAT';

-- TASK 9
SELECT ITEM_ID, DESCRIPTION, ON_HAND * PRICE AS ON_HAND_VALUE
FROM ITEM
WHERE ON_HAND * PRICE >= 1500;

-- TASK 10
SELECT ITEM_ID, DESCRIPTION
FROM ITEM
WHERE CATEGORY IN ('FSH', 'BRD');