-- ASSIGNMENT 10

-- TASK 1
SELECT CUSTOMER.CUST_ID, FIRST_NAME, LAST_NAME
FROM CUSTOMER, INVOICES, INVOICE_LINE, ITEM
WHERE CUSTOMER.CUST_ID = INVOICES.CUST_ID
	AND INVOICES.INVOICE_NUM = INVOICE_LINE.INVOICE_NUM
	AND INVOICE_LINE.ITEM_ID = ITEM.ITEM_ID
	AND ITEM.DESCRIPTION = 'Wild Bird Food (25 lb)';

-- TASK 2
SELECT INVOICE_NUM, INVOICE_DATE
FROM INVOICES
WHERE CUST_ID IN(SELECT CUST_ID
	FROM CUSTOMER
	WHERE FIRST_NAME = 'James'
	AND LAST_NAME = 'Gonzalez');

-- TASK 3
SELECT INVOICES.INVOICE_NUM, INVOICES.INVOICE_DATE
FROM INVOICES, INVOICE_LINE, ITEM
WHERE INVOICES.INVOICE_NUM = INVOICE_LINE.INVOICE_NUM
	AND ITEM.ITEM_ID = INVOICE_LINE.ITEM_ID
	AND ITEM.DESCRIPTION = 'Wild Bird Food (25 lb)';

-- TASK 4
SELECT DISTINCT INVOICES.INVOICE_NUM, INVOICE_DATE
FROM INVOICES, INVOICE_LINE, ITEM, CUSTOMER
WHERE INVOICES.INVOICE_NUM = INVOICE_LINE.INVOICE_NUM
	AND INVOICE_LINE.ITEM_ID = ITEM.ITEM_ID
	AND INVOICES.CUST_ID = CUSTOMER.CUST_ID
	AND (ITEM.DESCRIPTION = 'Wild Bird Food (25 lb)' 
	OR (CUSTOMER.FIRST_NAME = 'James' AND CUSTOMER.LAST_NAME = 'Gonzalez'));

-- TASK 5
SELECT DISTINCT INVOICES.INVOICE_NUM, INVOICES.INVOICE_DATE
FROM INVOICES, INVOICE_LINE, ITEM, CUSTOMER
WHERE INVOICES.INVOICE_NUM = INVOICE_LINE.INVOICE_NUM
	AND INVOICE_LINE.ITEM_ID = ITEM.ITEM_ID
	AND INVOICES.CUST_ID = CUSTOMER.CUST_ID
	AND (ITEM.DESCRIPTION = 'Wild Bird Food (25 lb)'
	OR (CUSTOMER.FIRST_NAME = 'James' AND CUSTOMER.LAST_NAME = 'Gonzalez'));

-- TASK 6
SELECT DISTINCT INVOICES.INVOICE_NUM, INVOICES.INVOICE_DATE
FROM INVOICES, INVOICE_LINE, ITEM, CUSTOMER
WHERE INVOICES.INVOICE_NUM = INVOICE_LINE.INVOICE_NUM
	AND INVOICE_LINE.ITEM_ID = ITEM.ITEM_ID
	AND INVOICES.CUST_ID = CUSTOMER.CUST_ID
	AND DESCRIPTION <> 'Wild Bird Food (25 lb)'
	AND FIRST_NAME = 'James'
	AND LAST_NAME = 'Gonzalez';

-- TASK 7
SELECT ITEM_ID, DESCRIPTION, PRICE, CATEGORY
FROM ITEM
WHERE PRICE < ALL(SELECT PRICE FROM ITEM WHERE CATEGORY = 'CAT');

-- TASK 8
SELECT ITEM.ITEM_ID, ITEM.DESCRIPTION, ITEM.ON_HAND, INVOICE_NUM, QUANTITY 
FROM ITEM
LEFT JOIN INVOICE_LINE ON (INVOICE_LINE.ITEM_ID = ITEM.ITEM_ID) ORDER BY ITEM_ID;

-- TASK 9
SELECT ITEM_ID, DESCRIPTION, PRICE, CATEGORY
FROM ITEM
WHERE PRICE < ANY (SELECT PRICE FROM ITEM WHERE CATEGORY = 'CAT');

-- TASK 10
SELECT SALES_REP.REP_ID, SALES_REP.FIRST_NAME AS REP_FIRST_NAME, SALES_REP.LAST_NAME AS REP_LAST_NAME, CUSTOMER.CUST_ID, CUSTOMER.FIRST_NAME AS CUST_FIRST_NAME, CUSTOMER.LAST_NAME AS CUST_LAST_NAME 
FROM CUSTOMER, SALES_REP
WHERE CUSTOMER.REP_ID = SALES_REP.REP_ID
ORDER BY REP_ID;