-- TASK 1
SELECT ASSIGN_NUM, PROJ_NUM, EMP_NUM
FROM ASSIGNMENT_3NF;

-- TASK 2
SELECT *
FROM EMPLOYEE_3NF;

SELECT * FROM ASSIGNMENT_3NF;

-- TASK 3
SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEE_3NF
WHERE EMP_HIREDATE >= '2000-01-01';

-- TASK 4
SELECT ASSIGN_NUM, ASSIGN_HOURS
FROM ASSIGNMENT_3NF
WHERE ASSIGN_CHG_HOUR > 50;

SELECT * FROM ASSIGNMENT_3NF;

-- TASK 5
SELECT EMP_NUM, JOB_CODE
FROM EMPLOYEE_3NF
WHERE JOB_CODE IN('502', '503');

SELECT * FROM EMPLOYEE_3NF;