-- TASK 1
SELECT ASSIGN_NUM, ASSIGN_DATE, PROJ_NUM 
FROM ASSIGNMENT_3NF
WHERE EMP_NUM LIKE '10%';

SELECT * FROM ASSIGNMENT_3NF;

-- TASK 2
SELECT *
FROM ASSIGNMENT_3NF
ORDER BY ASSIGN_DATE;

SELECT *
FROM ASSIGNMENT_3NF
ORDER BY ASSIGN_DATE DESC;

SELECT *
FROM ASSIGNMENT_3NF
ORDER BY ASSIGN_CHARGE DESC;


-- TASK 3
SELECT COUNT(*)
FROM ASSIGNMENT_3NF
WHERE ASSIGN_CHARGE > 200;

-- TASK 4
SELECT ASSIGN_NUM, ASSIGN_HOURS, ASSIGN_CHARGE
FROM ASSIGNMENT_3NF
WHERE ASSIGN_HOURS > (SELECT AVG(ASSIGN_HOURS) FROM ASSIGNMENT_3NF);

SELECT AVG(ASSIGN_HOURS) AS AVG_ASSIGN_HOURS
FROM ASSIGNMENT_3NF;

-- TASK 5
SELECT SUM(ASSIGN_CHARGE)
FROM ASSIGNMENT_3NF
WHERE ASSIGN_DATE = '2022-03-06';

SELECT ASSIGN_CHARGE, ASSIGN_DATE
FROM ASSIGNMENT_3NF
WHERE ASSIGN_DATE = '2022-03-06';